# Generated by Django 5.0.6 on 2024-08-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
