# Generated by Django 5.0.6 on 2024-08-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='opay_transaction_id',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
