# Generated by Django 5.0.6 on 2024-08-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid',
            new_name='payment_id',
        ),
    ]
